defaults:
  - default
  - _self_

# checkpoint
checkpoint_path: '/kaggle/input/mddial-training/gpt2_bc_20q.pt'   # nếu bạn có pretrained checkpoint, nếu không để null hoặc xóa dòng này
save_path: '/kaggle/working/'

# env
env_name: mddial
env_load_path: '/kaggle/input/mddial-training/mddial_t5_base_oracle.pt'

# training hyperparameters
rollout_size: 32              # có thể giảm nếu MDDial nặng hơn 20Q
batch_size: 8                 # tương tự, giảm nếu bị OOM
iterations: 70
epochs: 25
actor_epochs: 3
warmup_iter: 0
grad_accum_steps: 32
critic_lr: 2e-5
lm_lr: 1e-6
max_conversation_length: 20


# wandb logging
use_wandb: true
project_name: 'llm_rl_mddial'
run_name: 'archer-mddial'
